### ISSUE TITLE
OSGeo mantra

### ISSUE THREAD

**Issue by lnicola** [geo-system/qgis-smartsdi#1]
Hi! You asked for a mantra, but your mail server is down:

```
<geo-system@geo-system.com.pl>: connect to
    geo-system.com.pl[62.129.234.189]:25: Connection timed out
```

Please get in touch with me once it's fixed.

**Comment by lnicola** [comment]
That's Fastmail, not my email client. IIRC servers are always supposed to accept connections on port 25.

**Comment by lnicola** [comment]
I sent you the mantra from a Gmail address, did you receive it?

**Comment by geo-system** [comment]
Yes, we got it.
Thank you!
